GET http://127.0.0.1:8002/api/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJpdiI6IjM3UGJGdE43WG1RQ1IyaHlldkhMV3c9PSIsInZhbHVlIjoiR3V2ZWd0UHdtejAraW1vdTJNVndJYjl1UU83RitvbE51QkFxL0VaMkl3RW1rVjY5UzFjdFJ0c2VjV3NKV05jcWJDZlpRcm1JSkwwUFpFUG9sSXRlejBrY25MT2VqTGdDeFpCWS8xM3I5TjVDZVczeE1SS3llWVRBYTdVVjRMdUwiLCJtYWMiOiJhNzBkMjYxYzQzZjk4NmQxNGQxYmE3ZWI3NTlhMmIxNjk1YTkwYzMwYjM5MWIxZTllNmI5MzBjYjE3NTdlNmM2IiwidGFnIjoiIn0%3D
